// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(PulsacionesContext))]
    [Migration("20220729054428_UpdateBD")]
    partial class UpdateBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entidad.Administrador", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.HasKey("Cedula");

                    b.ToTable("Administradors");
                });

            modelBuilder.Entity("Entidad.Estudiante", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text");

                    b.Property<int>("ParcialPractico")
                        .HasColumnType("int");

                    b.Property<int>("ParcialTeorico")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.HasKey("Cedula");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Entidad.Instructor", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.HasKey("Cedula");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Entidad.Persona", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<decimal>("Pulsacion")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.HasKey("Identificacion");

                    b.ToTable("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
